name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:

      - name: Check out
        uses: actions/checkout@v2.3.2

      - name: brew pull & reset & tap
        run: |
          brew update-reset "$(brew --repository)"
          brew update-reset "$(brew --repository homebrew/cask)"
          mkdir -p $(brew --repo)/Library/Taps/mdogan
          ln -s $GITHUB_WORKSPACE $(brew --repo)/Library/Taps/mdogan/homebrew-zulu
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install jdk7
        run: brew install --cask zulu-jdk7
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install jdk8
        run: brew install --cask zulu-jdk8
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install jdk11
        run: brew install --cask zulu-jdk11
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install jdk13
        run: brew install --cask zulu-jdk13
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install jdk15
        run: brew install --cask zulu-jdk15
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1

      - name: install mission control
        run: brew install --cask zulu-mc
        env:
          HOMEBREW_COLOR: 1
          HOMEBREW_DEVELOPER: 1
