name: JDK10

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/reusable-cask-checks.yml'
      - 'Casks/zulu-jdk10.rb'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/reusable-cask-checks.yml'
      - 'Casks/zulu-jdk10.rb'

jobs:
  check:
    uses: ./.github/workflows/reusable-cask-checks.yml
    with:
      jdk-version: 10
