name: JDK22

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/reusable-cask-checks.yml'
      - 'Casks/zulu-jdk22.rb'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/reusable-cask-checks.yml'
      - 'Casks/zulu-jdk22.rb'

jobs:
  # This step is necessary for using `./github/workflows/*.yml` on the current branch, and it could be run on `ubuntu-latest`.
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  check:
    needs: checkout
    uses: ./.github/workflows/reusable-cask-checks.yml
    with:
      jdk-version: 22
