name: JDK21

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/reusable-cask-checks.yml'
      - 'Casks/zulu-jdk21.rb'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/reusable-cask-checks.yml'
      - 'Casks/zulu-jdk21.rb'

jobs:
  check:
    uses: ./.github/workflows/reusable-cask-checks.yml
    with:
      jdk-version: 21
