name: JDK22

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/reusable-cask-checks.yml'
      - 'Casks/zulu-jdk22.rb'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/reusable-cask-checks.yml'
      - 'Casks/zulu-jdk22.rb'

jobs:
  check:
    uses: goooler/homebrew-zulu/.github/workflows/reusable-cask-checks.yml@master
    with:
      jdk-version: 22
