name: Reusable Brew Cask Checks

on:
  workflow_call:
    inputs:
      jdk-version:
        description: 'Zulu JDK version to install, e.g. jdk11, jdk17, mc (special one for Mission Control), etc.'
        required: true
        type: string

jobs:
  check:
    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        os:
          - macos-latest # Based on arm64.
          - macos-15-intel # Based on x64.
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up Homebrew Tap
        run: |
          brew update-reset "$(brew --repository)"
          brew update-reset "$(brew --repository homebrew/cask)"
          TAP_BASE=$(brew --taps)/${{ github.repository_owner }}
          mkdir -p $TAP_BASE
          ln -s $GITHUB_WORKSPACE $TAP_BASE/${{ github.event.repository.name }}
      - name: install jdk
        run: brew install zulu-${{ inputs.jdk-version }}
      - name: uninstall jdk
        run: brew uninstall zulu-${{ inputs.jdk-version }}
      - name: audit casks
        run: brew audit --strict zulu-${{ inputs.jdk-version }}
