name: Upgrade Casks

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  upgrade:
    name: Upgrade Casks
    runs-on: ubuntu-latest
    if: github.repository == 'mdogan/homebrew-zulu'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Run Updater
        run: |
          cd updater
          ./gradlew run --args='..'

      - name: Generate Github Token
        uses: tibdex/github-app-token@v2
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch-token: ${{ steps.generate_token.outputs.token }}
          commit-message: Upgrade JDK Casks to the latest versions
          title: Upgrade JDK Casks
          body: |
            Upgraded JDK Casks to the latest versions.

            _Auto-generated by `Upgrade Casks` Github workflow._
          branch: upgrade-casks
          delete-branch: true
